### ISSUE TITLE
Convert to CRA

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/greenhouse-exporter#56]
Instead of having to maintain configuration files and dependencies for this project can you convert it to use [Create React APP](https://create-react-app.dev/) like our other projects please.

**Comment by andesol** [comment]
Closing this for now, as CRA might not go well with the current architecture of the project.

**Comment by hatched** [comment]
Just to elaborate on the problem...

CRA does not allow you to have a development build that is output to disk and able to be hosted by another server (without hacks). In this project at the time of writing there is a python server that serves the app assets as well as the API endpoints. If we switch to CRA we'd have to connect to the API server separately which is out of scope at this time. 

This can be revisited if CRA adds this feature (although they have repeatedly rejected adding it in the past).
